# -*- coding: utf-8 -*-
"""drug_release_simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCbKv8iNiK7B9q5eC8rl_3Kb7wTHh9so
"""

import numpy as np
import matplotlib.pyplot as plt
# Parameters
C0 = 100  # Initial drug concentration (e.g., in mg)
k = 0.1   # Release rate constant
time = np.linspace(0, 50, 500)  # Time range (0 to 50 units, with 500 points)
# First-order release
C_first_order = C0 * np.exp(-k * time)

# Zero-order release
C_zero_order = C0 - k * time
C_zero_order = np.clip(C_zero_order, 0, None)  # Ensure no negative values
# Plot the release profiles
plt.figure(figsize=(10, 6))
plt.plot(time, C_first_order, label="First-Order Release", linestyle='--')
plt.plot(time, C_zero_order, label="Zero-Order Release", linestyle='-')
plt.title("Drug Release Profiles")
plt.xlabel("Time (hours)")
plt.ylabel("Drug Concentration (mg)")
plt.legend()
plt.grid()
plt.show()